/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.example.domain.Restaurant;

import java.util.Map;

public class App {
    Map<Number, Restaurant> restaurants;
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
