/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.example.domain.Registration;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test
    void oneCustomerInlineAndCheckStatus() {
        App classUnderTest = new App();
        Registration reg = new Registration(145, 10, 0933335625, "john@example.com");
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
